"""Custom map preset generated by map_editor.py.

This preset stores obstacle geometry as `[start, end)` rectangles compatible
with `MapGrid.add_obstacle_rect`.
"""

from typing import Final, TypeAlias

from core.map_grid import MapGrid

GridRectangle: TypeAlias = tuple[int, int, int, int]

BASE_MAP_ROWS: Final[int] = 55
BASE_MAP_COLS: Final[int] = 100

OBSTACLE_RECTANGLES: Final[tuple[GridRectangle, ...]] = (
    (0, 10, 0, 6),
    (0, 7, 39, 43),
    (0, 7, 47, 51),
    (0, 7, 54, 80),
    (0, 7, 83, 100),
    (2, 7, 9, 36),
    (7, 10, 9, 30),
    (10, 39, 39, 43),
    (10, 39, 47, 51),
    (10, 13, 54, 71),
    (10, 39, 83, 100),
    (13, 55, 0, 6),
    (13, 31, 54, 80),
    (28, 39, 9, 36),
    (31, 39, 54, 66),
    (31, 36, 71, 80),
    (36, 39, 71, 77),
    (42, 45, 9, 71),
    (42, 52, 83, 100),
    (45, 52, 9, 75),
    (52, 55, 9, 100),
)


def _validate_scale_factor(scale_factor: object) -> int:
    """Validates and returns a positive integer map scale factor."""
    if (
        isinstance(scale_factor, bool)
        or not isinstance(scale_factor, int)
        or scale_factor <= 0
    ):
        raise ValueError(
            "scale_factor must be a positive integer; "
            f"received {scale_factor!r}."
        )

    return scale_factor


def _scale_rectangle(rectangle: GridRectangle, scale_factor: int) -> GridRectangle:
    """Scales a `[start, end)` rectangle by the same factor in both axes."""
    row_start, row_end, col_start, col_end = rectangle
    return (
        row_start * scale_factor,
        row_end * scale_factor,
        col_start * scale_factor,
        col_end * scale_factor,
    )


def create_custom_map(scale_factor: int = 1) -> MapGrid:
    """Creates a custom `MapGrid` from exported obstacle rectangles."""
    valid_scale_factor = _validate_scale_factor(scale_factor)

    map_grid = MapGrid(
        rows=BASE_MAP_ROWS * valid_scale_factor,
        cols=BASE_MAP_COLS * valid_scale_factor,
    )

    for rectangle in OBSTACLE_RECTANGLES:
        map_grid.add_obstacle_rect(*_scale_rectangle(rectangle, valid_scale_factor))

    return map_grid


__all__ = ["create_custom_map"]
